ARG VARIANT=1-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/go:0-${VARIANT}

RUN apt update && apt install --yes openssh-server git

RUN go install -v golang.org/x/tools/gopls@latest
RUN go install -v github.com/ramya-rao-a/go-outline@latest
RUN go install -v github.com/cweill/gotests/gotests@latest
RUN go install -v github.com/go-delve/delve/cmd/dlv@latest
RUN go install -v honnef.co/go/tools/cmd/staticcheck@latest 
RUN go install -v github.com/davidrjenni/reftools/cmd/fillstruct@latest

CMD ["go mod tidy && service ssh restart && sleep infinity"]